# Generated by Django 5.2.9 on 2025-12-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='word_column',
            new_name='word_count',
        ),
    ]
