@BASE_URL = http://127.0.0.1:8000/api/v1/
GET {{BASE_URL}}/issues/
GET {{BASE_URL}}/issues/d65ac426-7a03-4b65-8d58-774a2f36fb42
POST {{BASE_URL}}/issues/
Content-Type: application/json

{
  "title": "The Greatest Issue",
  "description": "Destruction of the world is imminent",
  "priority":"high"
}

POST {{BASE_URL}}/users/
Content-Type: application/json

{
  "name":"Joshua Ayomide Ajiwojuolorun",
  "email":"ajiwojuolorunjoshua@gmail.com",
  "password":"User!12345",
  "username":"JoshAjikaze",
  "user_type":"admin"
}
